import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFlask,
  faDna,
  faGlobe,
  faBook,
  faPenFancy,
  faFileLines,
  faChartLine,
  faBullhorn,
  faRobot,
  faTrophy,
  faBolt,
  faMedal,
  faFire,
  faRocket,
  faBrain,
  faHandshake,
  faBullseye,
  faGraduationCap,
  faMicroscope,
  faBookOpen,
  faFlaskVial,
  faDna as faDnaAlt,
  faPenNib,
  faChartBar,
  faMagnifyingGlass,
  faFileContract,
  faUsers,
  faCalendarDays,
  faLocationDot,
  faBriefcase,
  faAward,
  faStar,
  faLightbulb,
  faVial,
  faSeedling,
  faCode,
  faLaptopCode,
  faShieldHalved,
  faClipboardList,
  faCircleCheck,
  faLock,
  faArrowRight,
  faWandMagicSparkles,
  type IconDefinition,
} from "@fortawesome/free-solid-svg-icons";

const ICON_MAP: Record<string, IconDefinition> = {
  flask: faFlask,
  dna: faDna,
  globe: faGlobe,
  book: faBook,
  pen: faPenFancy,
  file: faFileLines,
  chart: faChartLine,
  bullhorn: faBullhorn,
  robot: faRobot,
  trophy: faTrophy,
  bolt: faBolt,
  medal: faMedal,
  fire: faFire,
  rocket: faRocket,
  brain: faBrain,
  handshake: faHandshake,
  bullseye: faBullseye,
  graduation: faGraduationCap,
  microscope: faMicroscope,
  bookopen: faBookOpen,
  flaskvial: faFlaskVial,
  pennib: faPenNib,
  chartbar: faChartBar,
  search: faMagnifyingGlass,
  contract: faFileContract,
  users: faUsers,
  calendar: faCalendarDays,
  location: faLocationDot,
  briefcase: faBriefcase,
  award: faAward,
  star: faStar,
  lightbulb: faLightbulb,
  vial: faVial,
  seedling: faSeedling,
  code: faCode,
  laptop: faLaptopCode,
  shield: faShieldHalved,
  clipboard: faClipboardList,
  check: faCircleCheck,
  lock: faLock,
  arrow: faArrowRight,
  sparkles: faWandMagicSparkles,
  dnaalt: faDnaAlt,
};

export function FaIcon({
  name,
  className = "",
  size = "1x",
}: {
  name: string;
  className?: string;
  size?: "xs" | "sm" | "lg" | "1x" | "2x" | "3x";
}) {
  const icon = ICON_MAP[name] ?? faStar;
  return <FontAwesomeIcon icon={icon} className={className} size={size} />;
}
