import type {
  ResearchPhase,
  ResearchProject,
  Collaborator,
  Publication,
  Grant,
  Patent,
  KanbanTask,
  Badge,
  CommunityPost,
  ResearchEvent,
} from "./types";

export const RESEARCHER = {
  name: "Dr. Aryan Buha",
  department: "Department of Machine Learning",
  avatar: "https://i.pravatar.cc/150?img=33",
  impactScore: 94,
  hIndex: 12,
  totalCitations: 428,
  citationGrowth: 14,
  rank: 8,
};

export const initialProjects: ResearchProject[] = [
  {
    id: 1,
    title: "Deep Optimization with Sparse Graph Nets",
    field: "ML & Logic Graphs",
    progress: 84,
    citations: 24,
    coauthors: ["Dr. Helena Chen", "Prof. K. Sen"],
    sotaLevel: "Tier 1",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=240&fit=crop",
    status: "active",
  },
  {
    id: 2,
    title: "Multi-Agent Matrix for Solar Grids",
    field: "Decentralized Systems",
    progress: 52,
    citations: 8,
    coauthors: ["Dr. Marcus Vance"],
    sotaLevel: "Tier 2",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=240&fit=crop",
    status: "active",
  },
  {
    id: 3,
    title: "Distributed Vector Parsing Architecture",
    field: "LLM Compiler Kernels",
    progress: 30,
    citations: 12,
    coauthors: ["Dr. Aryan Buha", "Priya Patel"],
    sotaLevel: "Tier 1",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=240&fit=crop",
    status: "review",
  },
  {
    id: 4,
    title: "Federated Learning for Genomic Privacy",
    field: "Bioinformatics & Privacy",
    progress: 67,
    citations: 19,
    coauthors: ["Dr. Elena Rossi", "Dr. Helena Chen"],
    sotaLevel: "Tier 1",
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=240&fit=crop",
    status: "active",
  },
];

export const collaborators: Collaborator[] = [
  {
    id: "c1",
    name: "Dr. Helena Chen",
    title: "Associate Professor",
    institution: "MIT CSAIL",
    hIndex: 28,
    citations: 4200,
    avatar: "https://i.pravatar.cc/100?img=47",
    expertise: ["Graph Neural Networks", "Sparse Models", "NeurIPS"],
  },
  {
    id: "c2",
    name: "Dr. Marcus Vance",
    title: "Research Scientist",
    institution: "DeepMind",
    hIndex: 19,
    citations: 2100,
    avatar: "https://i.pravatar.cc/100?img=12",
    expertise: ["Multi-Agent Systems", "Reinforcement Learning"],
  },
  {
    id: "c3",
    name: "Dr. Elena Rossi",
    title: "Principal Investigator",
    institution: "ETH Zürich",
    hIndex: 22,
    citations: 3100,
    avatar: "https://i.pravatar.cc/100?img=45",
    expertise: ["Federated Learning", "Genomics", "Privacy"],
  },
  {
    id: "c4",
    name: "Prof. K. Sen",
    title: "Department Chair",
    institution: "IIT Bombay",
    hIndex: 35,
    citations: 8900,
    avatar: "https://i.pravatar.cc/100?img=52",
    expertise: ["Compiler Design", "HPC", "ML Systems"],
  },
  {
    id: "c5",
    name: "Priya Patel",
    title: "PhD Candidate",
    institution: "Stanford AI Lab",
    hIndex: 6,
    citations: 340,
    avatar: "https://i.pravatar.cc/100?img=32",
    expertise: ["LLM Kernels", "CUDA Optimization"],
  },
];

export const publications: Publication[] = [
  {
    id: "p1",
    title: "Sparse Graph Embeddings for Zero-Shot Node Classification",
    journal: "NeurIPS 2025",
    year: 2025,
    citations: 89,
    status: "published",
    authors: ["A. Buha", "H. Chen", "K. Sen"],
    doi: "10.5555/neurips.2025.14209",
  },
  {
    id: "p2",
    title: "Federated Genomic Models with Differential Privacy Guarantees",
    journal: "Nature Machine Intelligence",
    year: 2025,
    citations: 56,
    status: "published",
    authors: ["A. Buha", "E. Rossi"],
    doi: "10.1038/s42256-025-00142",
  },
  {
    id: "p3",
    title: "Multi-Agent Coordination in Decentralized Energy Grids",
    journal: "ICML 2026 (Under Review)",
    year: 2026,
    citations: 0,
    status: "review",
    authors: ["A. Buha", "M. Vance"],
  },
  {
    id: "p4",
    title: "Vector Parsing Kernels for Large Language Model Compilation",
    journal: "Draft Manuscript",
    year: 2026,
    citations: 0,
    status: "draft",
    authors: ["A. Buha", "P. Patel"],
  },
];

export const grants: Grant[] = [
  {
    id: "g1",
    title: "ERC Starting Grant — Sparse Neural Architectures",
    agency: "European Research Council",
    amount: "€1.5M",
    deadline: "Mar 14, 2027",
    status: "pending",
    progress: 72,
  },
  {
    id: "g2",
    title: "NIH R21 Exploratory — Genomic Privacy ML",
    agency: "National Institutes of Health",
    amount: "$275K",
    deadline: "Feb 02, 2027",
    status: "draft",
    progress: 45,
  },
  {
    id: "g3",
    title: "EU Horizon Cluster 1 — Green AI Systems",
    agency: "Horizon Europe",
    amount: "€420K",
    deadline: "Jan 18, 2027",
    status: "awarded",
    progress: 100,
  },
  {
    id: "g4",
    title: "NSF CAREER Award — Graph Learning Foundations",
    agency: "National Science Foundation",
    amount: "$500K",
    deadline: "Jul 22, 2026",
    status: "active",
    progress: 88,
  },
];

export const patents: Patent[] = [
  {
    id: "pat-1",
    title: "Sparse Graph Node Compression Method",
    stage: "Patent Filing",
    progress: 80,
    filingDate: "Jan 2026",
    inventors: ["A. Buha", "H. Chen"],
  },
  {
    id: "pat-2",
    title: "Distributed Vector Parsing Architecture",
    stage: "Research Validation",
    progress: 40,
    filingDate: "Mar 2026",
    inventors: ["A. Buha", "P. Patel"],
  },
  {
    id: "pat-3",
    title: "Privacy-Preserving Federated Genomic Pipeline",
    stage: "Prior Art Search",
    progress: 25,
    filingDate: "Q2 2026",
    inventors: ["A. Buha", "E. Rossi"],
  },
];

export const initialKanbanTasks: KanbanTask[] = [
  { id: 1, title: "Review literature matrix on graph embeddings", column: "todo", priority: "High", tags: ["Literature"] },
  { id: 2, title: "Draft experiment models using PyTorch API", column: "progress", priority: "Medium", tags: ["Experiment"] },
  { id: 3, title: "Submit Horizon grant report draft", column: "done", priority: "Low", tags: ["Grants"] },
  { id: 4, title: "Compile NeurIPS camera-ready figures", column: "progress", priority: "High", tags: ["Publication"] },
  { id: 5, title: "Schedule co-author sync with Dr. Chen", column: "todo", priority: "Medium", tags: ["Collaboration"] },
  { id: 6, title: "Run GPU benchmark on sparse model v2", column: "todo", priority: "High", tags: ["Experiment"] },
];

export const initialPhases: ResearchPhase[] = [
  {
    phase: 1,
    name: "Hypothesis & SOTA Review",
    desc: "Define the core research question, construct a bibliography map, and read 20 foundational SOTA papers.",
    details: "Set up baseline ML diagnostic objectives. Check current ArXiv and NeurIPS publication overlaps.",
    action: "Review Citations SOTA",
    category: "Hypothesis",
    tags: ["SOTA Review", "Lit Survey", "BibTeX Maps"],
    gradient: "from-violet-400 to-indigo-500",
    color: "violet",
    initials: "P1",
    timeline: "Months 1 - 2",
    tasks: [
      { id: "rp1-t1", title: "Read 20 foundational SOTA papers in the target domain", done: true },
      { id: "rp1-t2", title: "Construct citation bibliography map", done: true },
      { id: "rp1-t3", title: "Draft target research question abstract", done: false },
    ],
  },
  {
    phase: 2,
    name: "Literature & Citation Catalog",
    desc: "Verify citation reference overlaps and catalogue 50 target papers into the BibTeX repository.",
    details: "Build reference tables. Identify critical architectural bottlenecks in prior designs.",
    action: "Run Citation Parser",
    category: "Literature",
    tags: ["BibTeX Parsing", "Citation catalog", "Overlap check"],
    gradient: "from-sky-400 to-blue-500",
    color: "sky",
    initials: "P2",
    timeline: "Months 2 - 3",
    tasks: [
      { id: "rp2-t1", title: "Catalogue 50 domain papers in LaTeX bibliography", done: true },
      { id: "rp2-t2", title: "Write BibTeX reference index scripts", done: false },
      { id: "rp2-t3", title: "Verify SOTA baseline compatibility", done: false },
    ],
  },
  {
    phase: 3,
    name: "Experiment & Benchmark Runs",
    desc: "Write PyTorch training scripts, configure GPU parameters, and analyze accuracy/loss curves.",
    details: "Initialize training sandbox loops. Validate metrics against the target SOTA thresholds.",
    action: "Launch Training Sandbox",
    category: "Experiment",
    tags: ["PyTorch Scripting", "GPU Sandbox Run", "Loss Analytics"],
    gradient: "from-emerald-400 to-teal-500",
    color: "emerald",
    initials: "P3",
    timeline: "Months 3 - 4",
    tasks: [
      { id: "rp3-t1", title: "Code primary model and training loops in PyTorch", done: false },
      { id: "rp3-t2", title: "Run GPU cloud benchmark models", done: false },
      { id: "rp3-t3", title: "Compile experimental loss/accuracy curves", done: false },
    ],
  },
  {
    phase: 4,
    name: "LaTeX Manuscript Drafting",
    desc: "Draft the LaTeX layout, optimize abstract terminology using AI, and write technical equations.",
    details: "Compile primary tables and graphics. Coordinate abstract reviews with co-authors.",
    action: "Optimize LaTeX Draft",
    category: "Drafting",
    tags: ["LaTeX Template", "AI Terminology", "Equations Compiler"],
    gradient: "from-indigo-400 to-purple-500",
    color: "indigo",
    initials: "P4",
    timeline: "Months 4 - 5",
    tasks: [
      { id: "rp4-t1", title: "Draft abstract & intro in standard LaTeX formats", done: false },
      { id: "rp4-t2", title: "Compile figures, diagrams & SOTA comparison tables", done: false },
      { id: "rp4-t3", title: "Submit first draft to department co-authors", done: false },
    ],
  },
  {
    phase: 5,
    name: "Camera-Ready Submission",
    desc: "Format references, submit to ArXiv, upload code to GitHub, and finalize patent filing drafts.",
    details: "Ensure double-blind guidelines. Compile LaTeX sources for target journals.",
    action: "Submit to Conference",
    category: "Submission",
    tags: ["ArXiv Submission", "GitHub Code Release", "Patent Drafting"],
    gradient: "from-fuchsia-400 to-rose-500",
    color: "rose",
    initials: "P5",
    timeline: "Months 5 - 6",
    tasks: [
      { id: "rp5-t1", title: "Submit camera-ready manuscript to ArXiv/NeurIPS", done: false },
      { id: "rp5-t2", title: "Publish verified replication code to GitHub", done: false },
      { id: "rp5-t3", title: "File provisional patent sequences for the model", done: false },
    ],
  },
];

export const badges: Badge[] = [
  { title: "First Abstract", desc: "Polished target abstract draft", icon: "🚀", earned: true, color: "sky" },
  { title: "Streak Scholar", desc: "7-day active research streak", icon: "🔥", earned: true, color: "rose" },
  { title: "SOTA Master", desc: "Analyzed 50 lit references", icon: "🧠", earned: true, color: "violet" },
  { title: "Co-author Match", desc: "Matched compatibility check", icon: "🤝", earned: true, color: "emerald" },
  { title: "AI Pioneer", desc: "Completed AI abstract review", icon: "🤖", earned: true, color: "indigo" },
  { title: "Grant Hunter", desc: "Submitted 3 grant proposals", icon: "💰", earned: true, color: "amber" },
  { title: "Pitch Perfect", desc: "Presented methodology pitch", icon: "🎯", earned: false, color: "amber" },
  { title: "Published", desc: "Submit a research paper draft", icon: "📄", earned: false, color: "teal" },
  { title: "Grand Finale", desc: "Finalize paper print cameras", icon: "🎓", earned: false, color: "gold" },
];

export const communityPosts: CommunityPost[] = [
  {
    id: "post1",
    author: "Dr. Helena Chen",
    avatar: "https://i.pravatar.cc/80?img=47",
    role: "MIT CSAIL",
    content: "Just published our sparse graph embedding framework on ArXiv! Looking for collaborators on the federated extension. DM if interested in joint NeurIPS submission.",
    likes: 142,
    comments: 28,
    time: "2h ago",
    tags: ["Graph ML", "Open Call"],
  },
  {
    id: "post2",
    author: "Dr. Marcus Vance",
    avatar: "https://i.pravatar.cc/80?img=12",
    role: "DeepMind Research",
    content: "Hosting a virtual workshop on Multi-Agent Systems for Energy Grids next Thursday. Free registration — link in bio. Would love to see industry + academia crossover talks.",
    likes: 89,
    comments: 15,
    time: "5h ago",
    tags: ["Workshop", "Energy AI"],
  },
  {
    id: "post3",
    author: "Prof. K. Sen",
    avatar: "https://i.pravatar.cc/80?img=52",
    role: "IIT Bombay",
    content: "Congratulations to @Dr. Aryan Buha on the Nature MI acceptance! Exceptional work on privacy-preserving genomic models. Proud to have co-advised this trajectory.",
    likes: 256,
    comments: 42,
    time: "1d ago",
    tags: ["Milestone", "Genomics"],
  },
  {
    id: "post4",
    author: "Priya Patel",
    avatar: "https://i.pravatar.cc/80?img=32",
    role: "Stanford AI Lab",
    content: "Sharing our LLM kernel optimization benchmarks — 3.2× speedup on sparse attention layers. Code dropping on GitHub this weekend. Feedback welcome!",
    likes: 67,
    comments: 11,
    time: "2d ago",
    tags: ["LLM", "Open Source"],
  },
];

export const researchEvents: ResearchEvent[] = [
  {
    id: "e1",
    title: "NeurIPS 2026 — Sparse ML Workshop",
    date: "Dec 10-12, 2026",
    location: "Vancouver, Canada",
    type: "conference",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=300&fit=crop",
  },
  {
    id: "e2",
    title: "Grant Writing Masterclass",
    date: "Jul 8, 2026",
    location: "Virtual · Zoom",
    type: "workshop",
    image: "https://images.unsplash.com/photo-1517245386807-bb43d82acdcc?w=600&h=300&fit=crop",
  },
  {
    id: "e3",
    title: "ERC Starting Grant Deadline",
    date: "Mar 14, 2027",
    location: "Submission Portal",
    type: "deadline",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=600&h=300&fit=crop",
  },
  {
    id: "e4",
    title: "Department Research Seminar — Dr. Elena Rossi",
    date: "Jun 24, 2026",
    location: "Auditorium B, ML Building",
    type: "seminar",
    image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&h=300&fit=crop",
  },
];

export const activityFeed = [
  { icon: "📄", text: "NeurIPS submission moved to Phase 4 drafting", time: "12m ago", color: "#a78bfa" },
  { icon: "🔬", text: "GPU benchmark completed — 42% speedup verified", time: "1h ago", color: "#34d399" },
  { icon: "🤝", text: "Co-author sync scheduled with Dr. Helena Chen", time: "3h ago", color: "#38bdf8" },
  { icon: "💰", text: "Horizon Europe grant marked as awarded", time: "Yesterday", color: "#fbbf24" },
  { icon: "📊", text: "Citation index updated — h-index now 12", time: "2d ago", color: "#f472b6" },
];

export const citationChartData = [
  { month: "Dec", value: 280 },
  { month: "Jan", value: 310 },
  { month: "Feb", value: 345 },
  { month: "Mar", value: 378 },
  { month: "Apr", value: 402 },
  { month: "May", value: 428 },
];
