export const RESEARCH_STUDENT = {
  name: "Aryan Gajjar",
  avatar: "https://i.pravatar.cc/150?img=11",
  healthScore: 78,
  currentPosition: "MSc Research Student · Biotechnology & Molecular Biology",
  goal: "Publish first systematic review paper & secure biotech R&D internship at a top lab",
  recommendedNextStep: "Complete Abstract Writing in Research Arena — you're 82% through Literature Review",
  recommendedLink: "/app/research/research_arena",
  progressScore: 62,
  careerProgress: 58,
  researchArenaProgress: 72,
  projectProgress: 45,
  level: 4,
  xp: 1850,
  streak: 12,
  badgesEarned: 5,
};

export const missingSkills = [
  { skill: "Statistical Analysis (R/SPSS)", priority: "High", gap: 35 },
  { skill: "Western Blot Protocol", priority: "Medium", gap: 28 },
  { skill: "LaTeX Manuscript Formatting", priority: "High", gap: 42 },
  { skill: "Meta-Analysis Methods", priority: "Medium", gap: 22 },
];

export const progressOverview = [
  { label: "Career Arena", value: 58, color: "#38bdf8", link: "/app/research/career_arena", icon: "briefcase" },
  { label: "Research Arena", value: 72, color: "#a78bfa", link: "/app/research/research_arena", icon: "microscope" },
  { label: "Projects", value: 45, color: "#34d399", link: "/app/research/research_projects", icon: "flask" },
  { label: "Opportunities", value: 34, color: "#f472b6", link: "/app/research/opportunities", icon: "star" },
];

export const careerGoals = [
  {
    id: "scientist",
    title: "Research Scientist",
    desc: "Academic or industry R&D — hypothesis-driven experiments, publications, grant writing",
    icon: "flask",
    match: 92,
    gradient: "from-violet-500/20 to-indigo-500/10",
    accent: "#a78bfa",
    tagline: "Hypothesis-driven discovery & peer-reviewed impact",
  },
  {
    id: "biotech",
    title: "Biotechnology Researcher",
    desc: "Lab protocols, genomics, drug discovery pipelines, clinical translational research",
    icon: "dna",
    match: 88,
    gradient: "from-emerald-500/20 to-teal-500/10",
    accent: "#34d399",
    tagline: "Translational science from bench to bedside",
  },
  {
    id: "other",
    title: "Other Careers",
    desc: "Science communication, patent analyst, regulatory affairs, or hybrid roles",
    icon: "globe",
    match: 74,
    gradient: "from-amber-500/20 to-orange-500/10",
    accent: "#fbbf24",
    tagline: "Hybrid roles bridging science & society",
  },
];

export const careerRoadmapsByGoal: Record<
  string,
  {
    phase: string;
    progress: number;
    items: string[];
    fullRoadmap: {
      title: string;
      duration: string;
      milestones: { week: string; task: string; status: "done" | "active" | "upcoming" }[];
      skills: string[];
      resources: string[];
    };
  }[]
> = {
  scientist: [
    {
      phase: "Foundation Learning",
      progress: 75,
      items: ["Biochemistry fundamentals", "Research methodology", "Ethics & IRB basics"],
      fullRoadmap: {
        title: "Foundation Learning — Research Scientist Track",
        duration: "12 weeks",
        milestones: [
          { week: "Wk 1–2", task: "Core biochemistry & cell biology review", status: "done" },
          { week: "Wk 3–4", task: "Research design & hypothesis framing", status: "done" },
          { week: "Wk 5–6", task: "IRB ethics & responsible conduct training", status: "done" },
          { week: "Wk 7–8", task: "Literature mapping & gap identification", status: "active" },
          { week: "Wk 9–10", task: "Pilot experiment design", status: "upcoming" },
          { week: "Wk 11–12", task: "Foundation assessment & mentor review", status: "upcoming" },
        ],
        skills: ["Experimental design", "Scientific writing", "Data ethics", "Lab safety"],
        resources: ["Nature Masterclasses", "Coursera Research Methods", "NIH Ethics Module"],
      },
    },
    {
      phase: "Practical Skills",
      progress: 52,
      items: ["Lab techniques workshop", "Data visualization", "Scientific writing bootcamp"],
      fullRoadmap: {
        title: "Practical Skills — Research Scientist Track",
        duration: "10 weeks",
        milestones: [
          { week: "Wk 1–2", task: "PCR & gel electrophoresis certification", status: "done" },
          { week: "Wk 3–4", task: "R/Python data visualization workshop", status: "active" },
          { week: "Wk 5–6", task: "IMRaD manuscript structure bootcamp", status: "upcoming" },
          { week: "Wk 7–8", task: "Grant proposal writing practice", status: "upcoming" },
          { week: "Wk 9–10", task: "Peer review simulation & critique", status: "upcoming" },
        ],
        skills: ["PCR techniques", "R ggplot2", "LaTeX formatting", "Grant writing"],
        resources: ["Addgene Protocols", "ggplot2 cheatsheet", "Overleaf templates"],
      },
    },
    {
      phase: "Skill Gap Analysis",
      progress: 68,
      items: ["Self-assessment matrix", "Peer benchmark compare", "Mentor feedback loop"],
      fullRoadmap: {
        title: "Skill Gap Analysis — Research Scientist Track",
        duration: "6 weeks",
        milestones: [
          { week: "Wk 1", task: "Complete 48-point self-assessment matrix", status: "done" },
          { week: "Wk 2", task: "Benchmark against top 10% peers in cohort", status: "done" },
          { week: "Wk 3–4", task: "Mentor 1:1 feedback session & gap prioritization", status: "active" },
          { week: "Wk 5–6", task: "Personalized remediation plan & tracking", status: "upcoming" },
        ],
        skills: ["Self-reflection", "Benchmarking", "Goal setting", "Mentorship"],
        resources: ["Skill matrix template", "Peer comparison dashboard", "Mentor booking portal"],
      },
    },
  ],
  biotech: [
    {
      phase: "Foundation Learning",
      progress: 80,
      items: ["Molecular biology core", "Genomics fundamentals", "GMP lab standards"],
      fullRoadmap: {
        title: "Foundation Learning — Biotech Track",
        duration: "10 weeks",
        milestones: [
          { week: "Wk 1–2", task: "Molecular cloning & plasmid design", status: "done" },
          { week: "Wk 3–4", task: "NGS basics & sequence analysis intro", status: "done" },
          { week: "Wk 5–6", task: "GMP & biosafety level protocols", status: "done" },
          { week: "Wk 7–8", task: "CRISPR mechanism deep-dive", status: "active" },
          { week: "Wk 9–10", task: "Biotech industry landscape survey", status: "upcoming" },
        ],
        skills: ["Cloning", "NGS basics", "GMP compliance", "CRISPR theory"],
        resources: ["Addgene CRISPR guide", "NCBI BLAST tutorials", "Biocon GMP handbook"],
      },
    },
    {
      phase: "Practical Skills",
      progress: 55,
      items: ["Western blot mastery", "Cell culture techniques", "Bioinformatics pipeline"],
      fullRoadmap: {
        title: "Practical Skills — Biotech Track",
        duration: "12 weeks",
        milestones: [
          { week: "Wk 1–3", task: "Western blot protocol certification", status: "done" },
          { week: "Wk 4–6", task: "Mammalian cell culture & passaging", status: "active" },
          { week: "Wk 7–9", task: "RNA-seq pipeline with Galaxy/CyVerse", status: "upcoming" },
          { week: "Wk 10–12", task: "Drug screening assay design", status: "upcoming" },
        ],
        skills: ["Western blot", "Cell culture", "RNA-seq", "Assay design"],
        resources: ["Abcam WB guide", "ATCC cell culture manual", "Galaxy training"],
      },
    },
    {
      phase: "Skill Gap Analysis",
      progress: 72,
      items: ["Industry skill benchmark", "Lab competency audit", "Internship readiness score"],
      fullRoadmap: {
        title: "Skill Gap Analysis — Biotech Track",
        duration: "4 weeks",
        milestones: [
          { week: "Wk 1", task: "Industry skill benchmark vs Biocon/IIT roles", status: "done" },
          { week: "Wk 2", task: "Lab competency practical audit", status: "done" },
          { week: "Wk 3", task: "Internship readiness scoring (94% CSIR match)", status: "active" },
          { week: "Wk 4", task: "Final gap closure plan & application prep", status: "upcoming" },
        ],
        skills: ["Industry benchmarking", "Lab audit", "Application prep"],
        resources: ["Biocon internship guide", "CSIR application portal", "Mock interview kit"],
      },
    },
  ],
  other: [
    {
      phase: "Foundation Learning",
      progress: 60,
      items: ["Science communication basics", "IP & patent fundamentals", "Regulatory overview"],
      fullRoadmap: {
        title: "Foundation Learning — Hybrid Careers Track",
        duration: "8 weeks",
        milestones: [
          { week: "Wk 1–2", task: "Science writing for public audiences", status: "done" },
          { week: "Wk 3–4", task: "Patent filing basics & prior art search", status: "active" },
          { week: "Wk 5–6", task: "CDSCO/FDA regulatory framework intro", status: "upcoming" },
          { week: "Wk 7–8", task: "Career path mapping workshop", status: "upcoming" },
        ],
        skills: ["Sci-comm", "Patent search", "Regulatory basics", "Career mapping"],
        resources: ["WIPO patent guide", "CDSCO portal", "The Conversation writing tips"],
      },
    },
    {
      phase: "Practical Skills",
      progress: 40,
      items: ["Technical blogging", "Patent claim drafting", "Policy brief writing"],
      fullRoadmap: {
        title: "Practical Skills — Hybrid Careers Track",
        duration: "10 weeks",
        milestones: [
          { week: "Wk 1–3", task: "Publish 3 technical blog posts", status: "active" },
          { week: "Wk 4–6", task: "Draft sample patent claims for biotech invention", status: "upcoming" },
          { week: "Wk 7–10", task: "Write policy brief on gene editing regulation", status: "upcoming" },
        ],
        skills: ["Blogging", "Patent drafting", "Policy writing"],
        resources: ["Medium science pubs", "USPTO claim examples", "Brookings policy templates"],
      },
    },
    {
      phase: "Skill Gap Analysis",
      progress: 55,
      items: ["Role fit assessment", "Portfolio review", "Network mapping"],
      fullRoadmap: {
        title: "Skill Gap Analysis — Hybrid Careers Track",
        duration: "4 weeks",
        milestones: [
          { week: "Wk 1", task: "Role fit assessment (sci-comm vs patent vs regulatory)", status: "done" },
          { week: "Wk 2", task: "Portfolio review with industry mentor", status: "active" },
          { week: "Wk 3–4", task: "Professional network mapping & outreach plan", status: "upcoming" },
        ],
        skills: ["Role assessment", "Portfolio building", "Networking"],
        resources: ["LinkedIn outreach templates", "Portfolio examples", "Mentor matching"],
      },
    },
  ],
};

export const internshipRecommendations = [
  {
    org: "CSIR — National Chemical Laboratory",
    role: "Biotech Research Intern",
    match: 94,
    deadline: "Jul 15, 2026",
    location: "Pune, Maharashtra",
    duration: "3 months",
    stipend: "₹8,000/month",
    skills: ["Molecular biology", "PCR", "Data analysis"],
    description: "Work on antimicrobial peptide screening under Dr. Sanjay Patil. Hands-on lab experience with HPLC and mass spectrometry.",
    highlights: ["Publication opportunity", "Lab certification", "Mentor letter"],
  },
  {
    org: "Biocon R&D Centre",
    role: "Molecular Biology Intern",
    match: 89,
    deadline: "Aug 01, 2026",
    location: "Bangalore, Karnataka",
    duration: "6 months",
    stipend: "₹12,000/month",
    skills: ["Cell culture", "Western blot", "GMP protocols"],
    description: "Join the biosimilars team for upstream process development. Exposure to industrial biotech workflows and regulatory documentation.",
    highlights: ["PPO pathway", "Industry exposure", "Stipend + accommodation"],
  },
  {
    org: "IIT Bombay — Bioengineering Lab",
    role: "Summer Research Fellow",
    match: 86,
    deadline: "Jun 30, 2026",
    location: "Mumbai, Maharashtra",
    duration: "2 months",
    stipend: "₹10,000/month",
    skills: ["CRISPR", "Bioinformatics", "Scientific writing"],
    description: "Contribute to CRISPR-Cas9 plant model research under Dr. Priya Mehta. Ideal for students targeting PhD programs.",
    highlights: ["IIT certificate", "Co-authorship potential", "PhD prep"],
  },
];

export const researchArenaModules = [
  {
    id: "lit",
    title: "Literature Review",
    progress: 82,
    status: "active",
    icon: "book",
    desc: "Systematic search, PRISMA flow, citation matrix",
    materials: [
      { title: "PRISMA 2020 Checklist", type: "PDF", size: "2.4 MB" },
      { title: "Citation Matrix Template", type: "XLSX", size: "156 KB" },
      { title: "Systematic Review Guide", type: "PDF", size: "4.1 MB" },
    ],
    content: {
      summary: "Your systematic literature review on CRISPR gene editing in plant models. 47 papers screened, 23 included in final matrix.",
      papers: [
        { title: "CRISPR-Cas9 mediated genome editing in crop plants", authors: "Zhang et al., 2024", journal: "Nature Plants", relevance: 96 },
        { title: "Off-target effects in plant CRISPR applications", authors: "Liu & Wang, 2023", journal: "Plant Cell", relevance: 91 },
        { title: "Delivery methods for CRISPR in agriculture", authors: "Kumar et al., 2024", journal: "Trends Biotech", relevance: 88 },
        { title: "Regulatory landscape for gene-edited crops", authors: "Sharma et al., 2023", journal: "GM Crops", relevance: 82 },
      ],
      prismaStats: { identified: 312, screened: 47, included: 23, excluded: 24 },
      aiCopilot: "Ask: 'Summarize key themes across included papers' or 'Find gaps for my review section'",
    },
  },
  {
    id: "abstract",
    title: "Abstract Writing",
    progress: 45,
    status: "active",
    icon: "pen",
    desc: "Structured abstract templates, keyword optimization",
    materials: [
      { title: "IMRaD Abstract Template", type: "DOCX", size: "89 KB" },
      { title: "Keyword Optimization Guide", type: "PDF", size: "1.2 MB" },
      { title: "Sample Abstracts — Top Journals", type: "PDF", size: "3.8 MB" },
    ],
    content: {
      summary: "Draft structured abstract for your CRISPR plant editing review. Current version scored 78/100 on clarity index.",
      draft: {
        background: "CRISPR-Cas9 has revolutionized plant genome editing, yet off-target effects remain a critical concern for agricultural applications.",
        methods: "We conducted a systematic review of 23 peer-reviewed studies (2020–2024) following PRISMA guidelines.",
        results: "Delivery via ribonucleoprotein complexes showed 34% fewer off-target events compared to plasmid-based methods.",
        conclusion: "Optimized CRISPR protocols with validated gRNA design can accelerate crop improvement while maintaining biosafety standards.",
      },
      keywords: ["CRISPR-Cas9", "plant genome editing", "off-target effects", "agricultural biotechnology"],
      aiScore: { clarity: 78, structure: 85, keywords: 72 },
      aiCopilot: "Ask: 'Improve my background sentence' or 'Suggest 3 more keywords for Scopus indexing'",
    },
  },
  {
    id: "review",
    title: "Review Paper Writing",
    progress: 20,
    status: "upcoming",
    icon: "file",
    desc: "Section-by-section drafting, co-author workflow",
    materials: [
      { title: "Review Paper Structure Guide", type: "PDF", size: "2.1 MB" },
      { title: "Co-author Workflow Template", type: "DOCX", size: "234 KB" },
      { title: "Journal Submission Checklist", type: "PDF", size: "890 KB" },
    ],
    content: {
      summary: "Section-by-section review paper drafting. Introduction complete, Methods in progress.",
      sections: [
        { name: "Introduction", status: "done", words: 1240 },
        { name: "Methods", status: "active", words: 680 },
        { name: "Results & Discussion", status: "upcoming", words: 0 },
        { name: "Conclusion", status: "upcoming", words: 0 },
        { name: "References", status: "active", words: 0 },
      ],
      targetJournal: "Trends in Plant Science",
      coAuthors: ["Dr. Priya Mehta (Guide)", "Aryan Gajjar (Lead)"],
      aiCopilot: "Ask: 'Draft discussion paragraph comparing delivery methods' or 'Check reference formatting for Elsevier'",
    },
  },
  {
    id: "analytics",
    title: "Research Analytics",
    progress: 60,
    status: "active",
    icon: "chart",
    desc: "Descriptive stats, trend charts, significance tests",
    materials: [
      { title: "R Analysis Scripts Bundle", type: "ZIP", size: "5.6 MB" },
      { title: "SPSS Output Interpretation Guide", type: "PDF", size: "1.8 MB" },
      { title: "Sample Dataset — CRISPR Efficacy", type: "CSV", size: "2.3 MB" },
    ],
    content: {
      summary: "Statistical analysis of CRISPR editing efficiency across 5 plant species. Preliminary results show significant variation (p < 0.01).",
      stats: [
        { metric: "Mean editing efficiency", value: "67.3%", change: "+12%" },
        { metric: "Off-target rate", value: "2.1%", change: "-0.8%" },
        { metric: "Sample size (n)", value: "156", change: "" },
        { metric: "p-value (ANOVA)", value: "0.003", change: "significant" },
      ],
      charts: ["Editing efficiency by species", "Off-target vs gRNA score", "Temporal trend 2020–2024"],
      aiCopilot: "Ask: 'Run t-test on Arabidopsis vs Rice editing rates' or 'Generate APA-style results paragraph'",
    },
  },
];

export const researchArenaUnlock = [
  {
    id: "cfp",
    title: "Calls for Papers",
    icon: "bullhorn",
    desc: "Conference CFP scanner, deadline alerts, fit scoring",
    items: [
      { conf: "Plant Biology 2026", deadline: "Aug 15", fit: 91 },
      { conf: "ISBR — Biosafety Research", deadline: "Sep 01", fit: 87 },
      { conf: "Indian Science Congress", deadline: "Oct 05", fit: 78 },
    ],
  },
  {
    id: "ai",
    title: "AI Detection & Evaluation",
    icon: "robot",
    desc: "Plagiarism scan, AI-content check, originality score",
    scores: { originality: 94, aiContent: 8, plagiarism: 2, readability: 82 },
  },
];

export const projectSources = [
  { id: "guide", label: "Via Guide", desc: "Mentor-assigned research under faculty supervision" },
  { id: "buy", label: "Buy the Project", desc: "Curated project kits with roadmap & materials" },
];

export const studentProjects = [
  {
    id: 1,
    title: "CRISPR-Cas9 Gene Editing in Plant Models",
    guide: "Dr. Priya Mehta",
    progress: 52,
    roadmap: ["Literature survey", "Protocol design", "Pilot experiments", "Data analysis", "Draft manuscript"],
    currentStep: 3,
    image: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&h=240&fit=crop",
    field: "Plant Biotechnology",
    collaborators: 2,
    citations: 0,
    nextMilestone: "Complete pilot experiments by Jul 15",
  },
  {
    id: 2,
    title: "Antimicrobial Peptide Screening Assay",
    guide: "Self-initiated (Buy Project)",
    progress: 28,
    roadmap: ["Kit setup", "Baseline assays", "Screening runs", "Report compilation"],
    currentStep: 2,
    image: "https://images.unsplash.com/photo-1582719471137-c3967ffb1c42?w=400&h=240&fit=crop",
    field: "Microbiology",
    collaborators: 0,
    citations: 0,
    nextMilestone: "Finish baseline assays by Jun 25",
  },
];

export const buyableProjects = [
  {
    title: "Microbial Fuel Cell Prototype",
    price: "₹4,999",
    duration: "8 weeks",
    level: "Intermediate",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&h=240&fit=crop",
    includes: ["Complete kit", "Video tutorials", "Mentor Q&A sessions", "Certificate"],
    field: "Environmental Biotech",
  },
  {
    title: "IoT Soil Nutrient Monitor",
    price: "₹3,499",
    duration: "6 weeks",
    level: "Beginner",
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=240&fit=crop",
    includes: ["Sensor kit", "Arduino code", "Dashboard template", "Report template"],
    field: "AgriTech",
  },
  {
    title: "AI Plant Disease Classifier",
    price: "₹6,999",
    duration: "10 weeks",
    level: "Advanced",
    image: "https://images.unsplash.com/photo-1592982536997-4a4d4e4e4e4e?w=400&h=240&fit=crop",
    includes: ["Dataset (5000 images)", "PyTorch notebook", "Deployment guide", "Paper draft template"],
    field: "AI + Agriculture",
  },
];

export const opportunities = {
  internships: [
    {
      id: "int1",
      title: "CSIR Summer Internship",
      org: "CSIR-NCL Pune",
      type: "Internship",
      deadline: "Jul 15",
      stipend: "₹8,000/mo",
      location: "Pune",
      duration: "3 months",
      description: "Hands-on research in antimicrobial peptide discovery. Work with HPLC, mass spec, and bioinformatics pipelines.",
      requirements: ["MSc/BTech in Life Sciences", "Basic lab experience", "GPA > 7.5"],
      skills: ["Molecular biology", "HPLC", "Data analysis"],
    },
    {
      id: "int2",
      title: "Biocon R&D Fellowship",
      org: "Biocon Ltd.",
      type: "Internship",
      deadline: "Aug 01",
      stipend: "₹12,000/mo",
      location: "Bangalore",
      duration: "6 months",
      description: "Industrial biotech internship in biosimilars upstream process development. GMP environment exposure.",
      requirements: ["MSc Biotechnology", "Cell culture experience preferred", "Strong communication"],
      skills: ["Cell culture", "GMP", "Process development"],
    },
    {
      id: "int3",
      title: "DRDO Young Scientist Lab",
      org: "DRDO",
      type: "Internship",
      deadline: "Jun 28",
      stipend: "₹10,000/mo",
      location: "Hyderabad",
      duration: "2 months",
      description: "Defence biotech research on pathogen detection systems. Security clearance required.",
      requirements: ["Indian citizen", "MSc/MTech", "Defence research interest"],
      skills: ["Microbiology", "Biosensors", "Lab safety"],
    },
  ],
  research: [
    {
      id: "res1",
      title: "Open Call — Cancer Immunotherapy",
      org: "Tata Memorial Centre",
      type: "Research",
      deadline: "Rolling",
      stipend: "Fellowship",
      location: "Mumbai",
      duration: "12 months",
      description: "Research assistant position in tumor microenvironment studies. Co-authorship on publications expected.",
      requirements: ["MSc Life Sciences", "Immunology background", "Willing to work with clinical samples"],
      skills: ["Flow cytometry", "Immunology", "Scientific writing"],
    },
    {
      id: "res2",
      title: "PhD Prep Research Assistant",
      org: "IISc Bangalore",
      type: "Research",
      deadline: "Jul 20",
      stipend: "₹15,000/mo",
      location: "Bangalore",
      duration: "6 months",
      description: "Pre-PhD research assistant in computational biology lab. Strong pathway to PhD admission.",
      requirements: ["MSc with 75%+", "Python/R proficiency", "Publications preferred"],
      skills: ["Python", "Bioinformatics", "Machine learning"],
    },
  ],
  hackathons: [
    {
      id: "hack1",
      title: "BioHack India 2026",
      org: "BioHack Global",
      type: "Hackathon",
      deadline: "Sep 10",
      stipend: "₹2L prizes",
      location: "Virtual + Mumbai Finals",
      duration: "48 hours",
      description: "48-hour biotech innovation hackathon. Build solutions for healthcare, agriculture, or environment.",
      requirements: ["Team of 2–4", "Any discipline", "Pitch deck required"],
      skills: ["Innovation", "Teamwork", "Pitching"],
    },
    {
      id: "hack2",
      title: "Smart Agriculture Hack",
      org: "AgriTech India",
      type: "Hackathon",
      deadline: "Aug 22",
      stipend: "₹50K prizes",
      location: "Pune",
      duration: "36 hours",
      description: "Build IoT/AI solutions for Indian farmers. Mentorship from AgriTech founders included.",
      requirements: ["Team of 3–5", "Tech + domain mix", "Working prototype"],
      skills: ["IoT", "AI/ML", "Agriculture"],
    },
  ],
  competitions: [
    {
      id: "comp1",
      title: "National Science Congress",
      org: "NCSTC",
      type: "Competition",
      deadline: "Oct 05",
      stipend: "Medals + Grant",
      location: "Delhi",
      duration: "3 days",
      description: "Present your research poster at India's premier science event. State-level qualification required.",
      requirements: ["Research project", "State qualification", "Poster + oral presentation"],
      skills: ["Presentation", "Research communication"],
    },
    {
      id: "comp2",
      title: "Young Innovator Challenge",
      org: "DST India",
      type: "Competition",
      deadline: "Nov 12",
      stipend: "₹1L seed",
      location: "Virtual",
      duration: "2 months",
      description: "Innovation challenge for students with prototype solutions. Seed funding for top 10 teams.",
      requirements: ["Working prototype", "Innovation focus", "Video pitch"],
      skills: ["Innovation", "Prototyping", "Entrepreneurship"],
    },
  ],
  conferences: [
    {
      id: "conf1",
      title: "Indian Science Congress 2026",
      org: "ISC",
      type: "Conference",
      deadline: "Dec 01",
      stipend: "Travel grant",
      location: "Hyderabad",
      duration: "5 days",
      description: "India's largest science gathering. Student delegate passes available with travel grants.",
      requirements: ["Abstract submission", "Student ID", "Faculty recommendation"],
      skills: ["Networking", "Scientific communication"],
    },
    {
      id: "conf2",
      title: "Biotech Summit Mumbai",
      org: "BioConnect",
      type: "Conference",
      deadline: "Jul 30",
      stipend: "Student pass free",
      location: "Mumbai",
      duration: "2 days",
      description: "Industry-academia biotech summit. Startup showcase, job fair, and networking sessions.",
      requirements: ["Registration", "Life sciences background"],
      skills: ["Networking", "Industry awareness"],
    },
  ],
};

export const vaultBadges = [
  { title: "First Literature Matrix", desc: "Built your first systematic review matrix", icon: "book", earned: true, color: "sky" },
  { title: "Abstract Draft Complete", desc: "Polished target abstract draft", icon: "pen", earned: true, color: "violet" },
  { title: "7-Day Research Streak", desc: "7-day active research streak", icon: "fire", earned: true, color: "rose" },
  { title: "SOTA Master", desc: "Analyzed 50+ literature references", icon: "brain", earned: true, color: "indigo" },
  { title: "Co-author Match", desc: "Matched compatibility with a collaborator", icon: "handshake", earned: true, color: "emerald" },
  { title: "Review Paper Submitted", desc: "Submit a review paper draft", icon: "file", earned: false, color: "teal" },
  { title: "Conference Presenter", desc: "Present at a research conference", icon: "bullhorn", earned: false, color: "amber" },
  { title: "Grand Finale", desc: "Complete full research publication cycle", icon: "graduation", earned: false, color: "gold" },
];

export const vaultStats = [
  { label: "Badges Earned", value: "5", icon: "trophy", color: "amber" },
  { label: "Total XP", value: "1,850", icon: "bolt", color: "sky" },
  { label: "Current Level", value: "4", icon: "medal", color: "violet" },
  { label: "Streak Record", value: "12 days", icon: "fire", color: "rose" },
];

export const eventCategories = {
  conferences: [
    {
      title: "Indian Science Congress 2026",
      date: "Jan 3–7, 2027",
      location: "Hyderabad",
      image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=300&fit=crop",
      type: "Conference",
      speakers: 120,
      attendees: "5000+",
      description: "India's premier multidisciplinary science congress. Keynotes from Nobel laureates, student poster sessions, and industry expo.",
      highlights: ["Student travel grants", "Poster competition", "Industry networking"],
      registrationFee: "₹2,500 (student)",
    },
    {
      title: "International Biotech Conference",
      date: "Nov 12–14, 2026",
      location: "Mumbai",
      image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=600&h=300&fit=crop",
      type: "Conference",
      speakers: 45,
      attendees: "1200+",
      description: "Global biotech leaders discuss CRISPR, biosimilars, and personalized medicine. Startup pitch arena included.",
      highlights: ["CRISPR workshop", "Job fair", "Startup pitches"],
      registrationFee: "₹5,000 (student)",
    },
  ],
  competitions: [
    {
      title: "National Science Congress Finals",
      date: "Oct 05, 2026",
      location: "Delhi",
      image: "https://images.unsplash.com/photo-1517245386807-bb43d82acdcc?w=600&h=300&fit=crop",
      type: "Competition",
      speakers: 0,
      attendees: "800+",
      description: "Final round of India's largest student science competition. Present your research to national judges.",
      highlights: ["Gold/Silver/Bronze medals", "DST grant for winners", "Media coverage"],
      registrationFee: "Qualified only",
    },
    {
      title: "BioInnovate Student Challenge",
      date: "Sep 18, 2026",
      location: "Virtual",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=300&fit=crop",
      type: "Competition",
      speakers: 8,
      attendees: "300+",
      description: "48-hour virtual biotech innovation challenge. Build solutions for healthcare and agriculture.",
      highlights: ["₹1L seed funding", "Mentor matching", "Incubator fast-track"],
      registrationFee: "Free",
    },
  ],
  workshops: [
    {
      title: "Western Blot Masterclass",
      date: "Jul 8, 2026",
      location: "IIT Bombay Lab",
      image: "https://images.unsplash.com/photo-1532094349884-54311bbf2d88?w=600&h=300&fit=crop",
      type: "Workshop",
      speakers: 2,
      attendees: "30 seats",
      description: "Hands-on Western blot workshop with Dr. Priya Mehta. Covers sample prep, transfer, blocking, and imaging.",
      highlights: ["Lab certification", "Take-home protocol", "Troubleshooting guide"],
      registrationFee: "₹1,500",
    },
    {
      title: "LaTeX for Researchers Workshop",
      date: "Jun 24, 2026",
      location: "Virtual · Zoom",
      image: "https://images.unsplash.com/photo-1456513086530-9b0f3a5046fa?w=600&h=300&fit=crop",
      type: "Workshop",
      speakers: 1,
      attendees: "100 seats",
      description: "Master LaTeX for journal submissions. Covers Overleaf, BibTeX, figure placement, and journal templates.",
      highlights: ["Overleaf templates", "BibTeX mastery", "Journal formatting"],
      registrationFee: "₹500",
    },
  ],
  internships: [
    {
      title: "CSIR Summer Internship Orientation",
      date: "Jul 1, 2026",
      location: "CSIR-NCL Pune",
      image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=300&fit=crop",
      type: "Orientation",
      speakers: 5,
      attendees: "50 interns",
      description: "Orientation day for selected CSIR summer interns. Lab tour, safety briefing, and mentor introductions.",
      highlights: ["Lab tour", "Safety certification", "Mentor meet"],
      registrationFee: "Selected interns only",
    },
    {
      title: "Biocon R&D Open Day",
      date: "Aug 5, 2026",
      location: "Bangalore Campus",
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=300&fit=crop",
      type: "Open Day",
      speakers: 10,
      attendees: "200+",
      description: "Open campus day at Biocon R&D. Tour facilities, meet scientists, and learn about internship pathways.",
      highlights: ["Facility tour", "Scientist Q&A", "Internship applications"],
      registrationFee: "Free (register early)",
    },
  ],
};

export const PROGRESS_UNLOCK_THRESHOLD = 50;
