/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as HowRouteImport } from './routes/how'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUniversityRouteImport } from './routes/app.university'
import { Route as AppStartupRouteImport } from './routes/app.startup'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppOutcomesRouteImport } from './routes/app.outcomes'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppInvestorRouteImport } from './routes/app.investor'
import { Route as AppExpertsRouteImport } from './routes/app.experts'
import { Route as AppExecutionRouteImport } from './routes/app.execution'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppConsultantRouteImport } from './routes/app.consultant'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCareerRouteImport } from './routes/app.career'
import { Route as AppAssessmentRouteImport } from './routes/app.assessment'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversityRoute = AppUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupRoute = AppStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesRoute = AppOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorRoute = AppInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertsRoute = AppExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionRoute = AppExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultantRoute = AppConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/how': typeof HowRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/research': typeof AppResearchRoute
  '/app/startup': typeof AppStartupRoute
  '/app/university': typeof AppUniversityRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ecosystem': typeof EcosystemRoute
  '/how': typeof HowRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/research': typeof AppResearchRoute
  '/app/startup': typeof AppStartupRoute
  '/app/university': typeof AppUniversityRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/ecosystem': typeof EcosystemRoute
  '/how': typeof HowRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/research': typeof AppResearchRoute
  '/app/startup': typeof AppStartupRoute
  '/app/university': typeof AppUniversityRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ecosystem'
    | '/how'
    | '/platform'
    | '/pricing'
    | '/app/achievements'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/research'
    | '/app/startup'
    | '/app/university'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ecosystem'
    | '/how'
    | '/platform'
    | '/pricing'
    | '/app/achievements'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/research'
    | '/app/startup'
    | '/app/university'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/ecosystem'
    | '/how'
    | '/platform'
    | '/pricing'
    | '/app/achievements'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/research'
    | '/app/startup'
    | '/app/university'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EcosystemRoute: typeof EcosystemRoute
  HowRoute: typeof HowRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/university': {
      id: '/app/university'
      path: '/university'
      fullPath: '/app/university'
      preLoaderRoute: typeof AppUniversityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/startup': {
      id: '/app/startup'
      path: '/startup'
      fullPath: '/app/startup'
      preLoaderRoute: typeof AppStartupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outcomes': {
      id: '/app/outcomes'
      path: '/outcomes'
      fullPath: '/app/outcomes'
      preLoaderRoute: typeof AppOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor': {
      id: '/app/investor'
      path: '/investor'
      fullPath: '/app/investor'
      preLoaderRoute: typeof AppInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experts': {
      id: '/app/experts'
      path: '/experts'
      fullPath: '/app/experts'
      preLoaderRoute: typeof AppExpertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/execution': {
      id: '/app/execution'
      path: '/execution'
      fullPath: '/app/execution'
      preLoaderRoute: typeof AppExecutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultant': {
      id: '/app/consultant'
      path: '/consultant'
      fullPath: '/app/consultant'
      preLoaderRoute: typeof AppConsultantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessment': {
      id: '/app/assessment'
      path: '/assessment'
      fullPath: '/app/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppCareerRoute: typeof AppCareerRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppConsultantRoute: typeof AppConsultantRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExecutionRoute: typeof AppExecutionRoute
  AppExpertsRoute: typeof AppExpertsRoute
  AppInvestorRoute: typeof AppInvestorRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOutcomesRoute: typeof AppOutcomesRoute
  AppResearchRoute: typeof AppResearchRoute
  AppStartupRoute: typeof AppStartupRoute
  AppUniversityRoute: typeof AppUniversityRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAssessmentRoute: AppAssessmentRoute,
  AppCareerRoute: AppCareerRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppConsultantRoute: AppConsultantRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExecutionRoute: AppExecutionRoute,
  AppExpertsRoute: AppExpertsRoute,
  AppInvestorRoute: AppInvestorRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOutcomesRoute: AppOutcomesRoute,
  AppResearchRoute: AppResearchRoute,
  AppStartupRoute: AppStartupRoute,
  AppUniversityRoute: AppUniversityRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EcosystemRoute: EcosystemRoute,
  HowRoute: HowRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
