/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkspaceRouteImport } from './routes/app.workspace'
import { Route as AppUniversityRouteImport } from './routes/app.university'
import { Route as AppTrackerRouteImport } from './routes/app.tracker'
import { Route as AppStartupRouteImport } from './routes/app.startup'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOutcomesRouteImport } from './routes/app.outcomes'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppInvestorRouteImport } from './routes/app.investor'
import { Route as AppExpertsRouteImport } from './routes/app.experts'
import { Route as AppExecutionRouteImport } from './routes/app.execution'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDiscoveryRouteImport } from './routes/app.discovery'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppConsultantRouteImport } from './routes/app.consultant'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCareerRouteImport } from './routes/app.career'
import { Route as AppAssessmentRouteImport } from './routes/app.assessment'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversityRoute = AppUniversityRouteImport.update({
  id: '/university',
  path: '/university',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackerRoute = AppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupRoute = AppStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOutcomesRoute = AppOutcomesRouteImport.update({
  id: '/outcomes',
  path: '/outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorRoute = AppInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AppRoute,
} as any)
const AppExpertsRoute = AppExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutionRoute = AppExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultantRoute = AppConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerRoute = AppCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentRoute = AppAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/startup': typeof AppStartupRoute
  '/app/tracker': typeof AppTrackerRoute
  '/app/university': typeof AppUniversityRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/startup': typeof AppStartupRoute
  '/app/tracker': typeof AppTrackerRoute
  '/app/university': typeof AppUniversityRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/assessment': typeof AppAssessmentRoute
  '/app/career': typeof AppCareerRoute
  '/app/community': typeof AppCommunityRoute
  '/app/consultant': typeof AppConsultantRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/execution': typeof AppExecutionRoute
  '/app/experts': typeof AppExpertsRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/outcomes': typeof AppOutcomesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/startup': typeof AppStartupRoute
  '/app/tracker': typeof AppTrackerRoute
  '/app/university': typeof AppUniversityRoute
  '/app/workspace': typeof AppWorkspaceRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/discovery'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/profile'
    | '/app/reports'
    | '/app/research'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/startup'
    | '/app/tracker'
    | '/app/university'
    | '/app/workspace'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/discovery'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/profile'
    | '/app/reports'
    | '/app/research'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/startup'
    | '/app/tracker'
    | '/app/university'
    | '/app/workspace'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/achievements'
    | '/app/admin'
    | '/app/assessment'
    | '/app/career'
    | '/app/community'
    | '/app/consultant'
    | '/app/copilot'
    | '/app/discovery'
    | '/app/documents'
    | '/app/execution'
    | '/app/experts'
    | '/app/investor'
    | '/app/opportunities'
    | '/app/outcomes'
    | '/app/profile'
    | '/app/reports'
    | '/app/research'
    | '/app/roadmap'
    | '/app/settings'
    | '/app/startup'
    | '/app/tracker'
    | '/app/university'
    | '/app/workspace'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/university': {
      id: '/app/university'
      path: '/university'
      fullPath: '/app/university'
      preLoaderRoute: typeof AppUniversityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracker': {
      id: '/app/tracker'
      path: '/tracker'
      fullPath: '/app/tracker'
      preLoaderRoute: typeof AppTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/startup': {
      id: '/app/startup'
      path: '/startup'
      fullPath: '/app/startup'
      preLoaderRoute: typeof AppStartupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outcomes': {
      id: '/app/outcomes'
      path: '/outcomes'
      fullPath: '/app/outcomes'
      preLoaderRoute: typeof AppOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor': {
      id: '/app/investor'
      path: '/investor'
      fullPath: '/app/investor'
      preLoaderRoute: typeof AppInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experts': {
      id: '/app/experts'
      path: '/experts'
      fullPath: '/app/experts'
      preLoaderRoute: typeof AppExpertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/execution': {
      id: '/app/execution'
      path: '/execution'
      fullPath: '/app/execution'
      preLoaderRoute: typeof AppExecutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultant': {
      id: '/app/consultant'
      path: '/consultant'
      fullPath: '/app/consultant'
      preLoaderRoute: typeof AppConsultantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/career': {
      id: '/app/career'
      path: '/career'
      fullPath: '/app/career'
      preLoaderRoute: typeof AppCareerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assessment': {
      id: '/app/assessment'
      path: '/assessment'
      fullPath: '/app/assessment'
      preLoaderRoute: typeof AppAssessmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAssessmentRoute: typeof AppAssessmentRoute
  AppCareerRoute: typeof AppCareerRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppConsultantRoute: typeof AppConsultantRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExecutionRoute: typeof AppExecutionRoute
  AppExpertsRoute: typeof AppExpertsRoute
  AppInvestorRoute: typeof AppInvestorRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOutcomesRoute: typeof AppOutcomesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStartupRoute: typeof AppStartupRoute
  AppTrackerRoute: typeof AppTrackerRoute
  AppUniversityRoute: typeof AppUniversityRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppAdminRoute: AppAdminRoute,
  AppAssessmentRoute: AppAssessmentRoute,
  AppCareerRoute: AppCareerRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppConsultantRoute: AppConsultantRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExecutionRoute: AppExecutionRoute,
  AppExpertsRoute: AppExpertsRoute,
  AppInvestorRoute: AppInvestorRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOutcomesRoute: AppOutcomesRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResearchRoute: AppResearchRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStartupRoute: AppStartupRoute,
  AppTrackerRoute: AppTrackerRoute,
  AppUniversityRoute: AppUniversityRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
